theme: jekyll-theme-leap-day
title: GrondToon
description: Holistische muzieklessen ♪
tagline: Een site met diverse leskits van GrondToon - een cultuureducatief product, ontwikkeld door Kayleigh Beard, in samenwerking met Grond - school voor leven en Compenta. 
author: Kayleigh Beard
url: https://grondtoon.kayleighbeard.nl
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed